// const LEFT_UPPER_CORNER: char = '┌';
// const RIGHT_UPPER_CORNER: char = '┐';
// const LEFT_LOWER_CORNER: char = '└';
// const RIGHT_LOWER_CORNER: char = '┘';
// const CROSS: char = '┼';
// const UPPER_CROSS: char = '┬';
// const LEFT_CROSS: char = '├';
// const RIGHT_CROSS: char = '┤';
// const LOWER_CROSS: char = '┴';
// const VERTICAL_LINE: char = '─';
// const HORIZONTAL_LINE: char = '│';

// println!("┌────────────┬────────────┬────────────┬────────────┐");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("│    2048    │    2048    │    2048    │    2048    │");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("├────────────┼────────────┼────────────┼────────────┤");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("│    2048    │    2048    │    2048    │    2048    │");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("├────────────┼────────────┼────────────┼────────────┤");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("│    2048    │    2048    │    2048    │    2048    │");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("├────────────┼────────────┼────────────┼────────────┤");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("│    2048    │    2048    │    2048    │    2048    │");
// println!("│            │            │            │            │");
// println!("│            │            │            │            │");
// println!("└────────────┴────────────┴────────────┴────────────┘");
